### PR TITLE
Changed how datetime constructed

### PR DESCRIPTION
**Pull request by wrussell1999**
Unable to test it, but looking at your code, it creates a string in the correct format for the json.

### CODE REVIEW

**Comment by wrussell1999** [comment]
I have removed the Z on the end, which was used for UTC. I'm not sure if it requires another on the end. I saw that LZ does local time but not sure for Google calendar. There's dateutil or something from datetime that helps with this

**Review by wrussell1999 — COMMENTED** [review]
Renamed variables to prevent conflict and increase readability. Also added logging.

**Review by wrussell1999 — COMMENTED** [review]
Little tweaks to help with debugging. Only implemented on the Google Calendar part, but can easily be copied over to other files.

**Review by wrussell1999 — COMMENTED** [review]
Now works for different timezones

**Comment by tomhmoses** [comment]
Lovely work! Thanks

**Pull request merged**
